from . import dashboard
from . import appointments
from . import doctors
from . import prescriptions
from . import payment
from . import insurance
from . import patient
from . import staff
from . import inventory
from . import profile
from . import settings
from . import support
